casting_prog p skill_masturbate
mpnotrigger casting_prog 1
if sex($n == F) or sex($n == A) or sex($n == H)
mpoloadroom fromfile wankitems.cmare pussyjuice
mpecho $n rubs one off, creating $b.
else
if sex($n == M) or sex($n == O) or sex($n == U)
mpoloadroom fromfile wankitems.cmare cum
mpecho $n strokes one off, creating $b.
else
if islike($n '-GENDER +NEUTER')
mpechoat $n what are you going to wank!? You got NOTHING.
endif
endif
endif
~
